/** ARCH-01/F6.1 — SystemBoot-owned shutdown execution evidence; not an executor. */
import type { CleanupCapability, CleanupExecutionKind, ShutdownPhase, ShutdownVerdict } from './runtimeShutdownModel';
export interface ShutdownCleanupEvidence { readonly serviceId: string; readonly phase: ShutdownPhase; readonly startedAt: number; readonly finishedAt: number; readonly durationMs: number; readonly executionKind: CleanupExecutionKind; readonly quiesce: CleanupCapability; readonly drain: CleanupCapability; readonly cancel: CleanupCapability; readonly boundedTimeout: CleanupCapability; readonly inFlightBefore: null; readonly inFlightAfter: null; readonly stopOutcome: 'SUCCEEDED' | 'FAILED' | 'TIMED_OUT'; readonly disposeOutcome: 'SUCCEEDED' | 'FAILED' | 'TIMED_OUT'; readonly timeout: boolean; readonly failureReason: string | null; readonly dependencyOrderSource: 'LIFO_FALLBACK'; readonly provenance: readonly string[]; }
export interface ShutdownRunSnapshot { readonly runId: string | null; readonly lifecycleEpoch: number | null; readonly phase: ShutdownPhase; readonly startedAt: number | null; readonly finishedAt: number | null; readonly outcome: ShutdownVerdict; readonly recoverySuppressed: boolean; readonly rows: readonly ShutdownCleanupEvidence[]; readonly staleRecoveryCompletionCount: number; }
let current: ShutdownRunSnapshot = Object.freeze({ runId: null, lifecycleEpoch: null, phase: 'RUNNING', startedAt: null, finishedAt: null, outcome: 'UNKNOWN', recoverySuppressed: false, rows: Object.freeze([]), staleRecoveryCompletionCount: 0 });
export function beginSystemBootShutdown(runId: string, lifecycleEpoch: number, at: number): void { if (current.phase !== 'RUNNING' && current.finishedAt === null) return; current = Object.freeze({ runId, lifecycleEpoch, phase: 'QUIESCING', startedAt: at, finishedAt: null, outcome: 'UNKNOWN', recoverySuppressed: true, rows: Object.freeze([]), staleRecoveryCompletionCount: 0 }); }
export function recordSystemBootCleanup(row: ShutdownCleanupEvidence): void { if (current.finishedAt !== null) return; current = Object.freeze({ ...current, phase: 'STOPPING', rows: Object.freeze([...current.rows, Object.freeze(row)]) }); }
export function finishSystemBootShutdown(at: number): void { if (current.finishedAt !== null) return; const failed = current.rows.filter((x) => x.stopOutcome !== 'SUCCEEDED'); current = Object.freeze({ ...current, phase: 'STOPPED', finishedAt: at, outcome: failed.length ? 'PARTIAL' : 'COMPLETE' }); }
export function noteStaleRecoveryCompletion(): void { if (current.finishedAt === null) return; current = Object.freeze({ ...current, staleRecoveryCompletionCount: current.staleRecoveryCompletionCount + 1 }); }
export function getSystemBootShutdownSnapshot(): ShutdownRunSnapshot { return current; }
