/** ARCH-01 runtime registry/LAB — read-only evidence projection. */
import { memo, useCallback, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { readRuntimeServiceRegistryGraph } from '../../../platform/devtools/runtimeServiceRegistrySources';

export const RuntimeServiceRegistryScreen = memo(function RuntimeServiceRegistryScreen() {
  const [snapshot, setSnapshot] = useState(() => readRuntimeServiceRegistryGraph());
  const refresh = useCallback(() => setSnapshot(readRuntimeServiceRegistryGraph()), []);
  if (snapshot === null) return <div data-testid="runtime-service-registry" className="p-3 font-mono text-[10px]">KAYNAK YOK — sonuç uydurulmadı.</div>;
  const { shutdown, resources, observability, resilience } = snapshot;
  return <div className="flex h-full flex-col gap-2 overflow-y-auto" data-testid="runtime-service-registry">
    <div className="rounded border border-[var(--oem-line)] p-3"><div className="flex gap-2 font-mono text-[11px]"><ShieldCheck size={13} /> RUNTIME SERVICE REGISTRY — READ ONLY</div><button type="button" data-testid="rsr-refresh" onClick={refresh} className="mt-2 font-mono text-[9px]"><RefreshCw size={11} /> YENİLE</button></div>
    <section data-testid="rsr-resource" className="rounded border border-[var(--oem-line)] p-3 font-mono text-[9px]"><div>resource mode={resources.runtimeMode} · thermal={resources.thermalTier} · ceiling={resources.effectiveCeiling ?? 'UNKNOWN'} · memory={resources.memoryPressure} · workers={resources.workerSaturation}</div><div>tasks={resources.tasks.length} · provenance={resources.provenance.join(',')}</div>{resources.tasks.length === 0 ? <div data-testid="rsr-resource-empty">task registry measured 0</div> : resources.tasks.map((task) => <div key={task.taskId} data-testid={`rsr-task-${task.taskId}`}>{task.taskId} · class={task.resourceClass} · decision={task.decision} · actual={task.actualCounter ?? 'UNAVAILABLE'} · budget={task.grantedBudget ?? 'UNAVAILABLE'} · defer={task.deferCount ?? 'UNAVAILABLE'} · starvation={task.starvationRisk === null ? 'UNKNOWN' : String(task.starvationRisk)} · provenance={task.provenance.join(',')}</div>)}</section>
    <section data-testid="rsr-observability" className="rounded border border-[var(--oem-line)] p-3 font-mono text-[9px]"><div>observability evidence={observability.evidence.length} · kinds={observability.system.evidenceKinds.join(',')} · unknown={observability.summary.unknown} · stale={observability.summary.stale} · contradictions={observability.contradictions.length}</div>{observability.services.map((row) => <div key={row.serviceId} data-testid={`rsr-observation-${row.serviceId}`}>{row.serviceId} · lifecycle={row.lifecycle} · readiness={row.readiness} · health={row.health} · freshness={row.freshness} · epoch={row.lifecycleEpoch ?? 'UNKNOWN'} · kinds={row.evidenceKinds.join(',')} · contradiction={row.contradictions.length ? 'CONTRADICTORY' : 'NONE'} · provenance={row.provenance.join(',')}</div>)}</section>
    <section data-testid="rsr-resilience" className="rounded border border-[var(--oem-line)] p-3 font-mono text-[9px]"><div>degraded operation FULL={resilience.summary.FULL} · DEGRADED={resilience.summary.DEGRADED} · LIMITED={resilience.summary.LIMITED} · UNAVAILABLE={resilience.summary.UNAVAILABLE} · BLOCKED={resilience.summary.BLOCKED} · UNKNOWN={resilience.summary.UNKNOWN}</div>{resilience.capabilities.map((capability) => <div key={capability.capabilityId} data-testid={`rsr-capability-${capability.capabilityId}`}>{capability.capabilityId} · owner={capability.owner} · availability={capability.availability} · freshness={capability.freshness ?? 'UNKNOWN'} · epoch={capability.lifecycleEpoch ?? 'UNKNOWN'} · dependency={capability.dependencyClass ?? 'UNKNOWN'} · criticality={capability.criticality} · readiness={capability.readinessEvidence ?? 'KAYNAK YOK'} · health={capability.healthEvidence ?? 'KAYNAK YOK'} · blockers={capability.dependencyBlockers.join(',') || 'YOK'} · degradedBy={capability.degradedBy.join(',') || 'YOK'} · allow={capability.allowedOperations.join(',') || 'UNKNOWN'} · deny={capability.deniedOperations.join(',') || 'UNKNOWN'} · reason={capability.reason} · fallback={capability.fallback ?? 'UNKNOWN'} · provenance={capability.provenance.join(',')}</div>)}</section>
    <section data-testid="rsr-shutdown" className="rounded border border-[var(--oem-line)] p-3 font-mono text-[9px]"><div>shutdown run={shutdown.runId ?? 'KAYNAK YOK'} · phase={shutdown.phase} · outcome={shutdown.outcome}</div><div>recoverySuppressed={String(shutdown.recoverySuppressed)} · staleRecoveryCompletion={shutdown.staleRecoveryCompletionCount}</div>{shutdown.rows.length === 0 ? <div>KAYNAK YOK — cleanup row uydurulmadı.</div> : shutdown.rows.map((row) => <div key={`${row.serviceId}:${row.startedAt}`} data-testid={`shutdown-row-${row.serviceId}`}>{row.serviceId} · execution={row.executionKind} · quiesce={row.quiesce} · drain={row.drain} · cancel={row.cancel} · timeoutCapability={row.boundedTimeout} · outcome={row.disposeOutcome} · duration={row.durationMs} · order={row.dependencyOrderSource} · failure={row.failureReason ?? 'YOK'} · provenance={row.provenance.join(',')}</div>)}</section>
    {snapshot.entries.map((row) => <div key={row.descriptor.id} className="rounded border border-[var(--oem-line)] p-2 font-mono text-[9px]">{row.descriptor.id} · lifecycle={row.lifecycle} · readiness={row.readiness} · health={row.health}</div>)}
  </div>;
});
