import { CLEANUP_LEDGER_KEY } from '../cleanupLedger';
import {
  AccountScopedStorageRegistry,
} from './storageRegistry';
import type { AccountScopedStorageDescriptor } from './storageTypes';

export const KNOWN_LEGACY_SECURITY_KEYS = Object.freeze([
  'caros_pair_api_key',
]);

export const KNOWN_CAROS_PREFIXES = Object.freeze([
  'caros',
  'clp_',
  'pwa-',
]);

const DESCRIPTORS: readonly AccountScopedStorageDescriptor[] = [
  {
    id: 'cleanup-ledger',
    backend: 'LOCAL_STORAGE',
    scope: 'SECURITY_SYSTEM',
    sensitivity: 'OPERATIONAL',
    cleanupPolicies: ['MANAGED_EXTERNALLY'],
    physicalKey: CLEANUP_LEDGER_KEY,
    namespaceVersion: 1,
    ownerRequirements: { accountId: false, vehicleId: false },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'cleanup-ledger-integrity',
    valueFormat: 'JSON',
    description: 'Secret içermeyen durable cleanup state ve recovery marker.',
  },
  {
    id: 'critical-pin-hash',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
    ],
    physicalKey: 'caros_critical_pin_hash',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'OPAQUE',
    description: 'Legacy client-side critical-command PIN hash authority.',
  },
  {
    id: 'paired-vehicle-authority',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
    ],
    physicalKey: 'caros_pair_vehicle_id',
    legacyKeys: ['caros_pair_vehicle_name', 'caros_pair_vehicle_plate'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'OPAQUE',
    description: 'Legacy selected/paired vehicle identity and display metadata.',
  },
  {
    id: 'fleet-offline-queue',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
    ],
    keyPattern: 'caros.fleet.queue.*',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'NAMESPACE_EMPTY',
    valueFormat: 'JSON',
    description: 'Account suffix taşıyan fleet mutation queue ve corrupt quarantine.',
  },
  {
    id: 'ownership-snapshot',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
    ],
    keyPattern: 'caros.fleet.snapshot.*',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'RECORD_OWNER_MATCH',
    valueFormat: 'JSON',
    description: 'Server-verified fleet ownership/role snapshot.',
  },
  {
    id: 'pending-pairing',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
      'EXPIRE_EPHEMERAL',
    ],
    keyPattern: 'caros.fleet.pairing.*',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'NAMESPACE_EMPTY',
    valueFormat: 'JSON',
    description: 'Encrypted-code pending pairing claims; current key is user suffixed.',
  },
  {
    id: 'parking-location',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['PURGE_ON_LOGOUT', 'PURGE_ON_ACCOUNT_SWITCH'],
    physicalKey: 'caros_parking_spot',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'JSON',
    description: 'Legacy last parking location without embedded account/vehicle owner.',
  },
  {
    id: 'fuel-log',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['PURGE_ON_LOGOUT', 'PURGE_ON_ACCOUNT_SWITCH'],
    physicalKey: 'caros_fuel_log',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'JSON',
    description: 'Legacy user-entered fuel history without owner namespace.',
  },
  {
    id: 'maintenance-log',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['PURGE_ON_LOGOUT', 'PURGE_ON_ACCOUNT_SWITCH'],
    physicalKey: 'caros_service_log',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'JSON',
    description: 'Legacy maintenance state without owner namespace.',
  },
  {
    id: 'push-subscription',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: [
      'PURGE_ON_LOGOUT',
      'PURGE_ON_ACCOUNT_SWITCH',
      'PURGE_ON_SECURITY_RESET',
    ],
    physicalKey: 'clp_push_sub',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'JSON',
    description: 'Push subscription fallback including endpoint/key material.',
  },
  {
    id: 'speed-alert',
    backend: 'LOCAL_STORAGE',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['PURGE_ON_LOGOUT', 'PURGE_ON_ACCOUNT_SWITCH'],
    physicalKey: 'caros_speed_alert',
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'KEY_ABSENT',
    valueFormat: 'JSON',
    description: 'Legacy vehicle speed alert configuration.',
  },
  {
    id: 'device-theme',
    backend: 'LOCAL_STORAGE',
    scope: 'GLOBAL_DEVICE',
    sensitivity: 'PREFERENCE',
    cleanupPolicies: ['RETAIN_DEVICE_PREFERENCE'],
    physicalKey: 'caros-theme',
    legacyKeys: ['pwa-theme', 'caros-theme-studio'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: false, vehicleId: false },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'device-theme-shape',
    valueFormat: 'OPAQUE',
    description: 'Allowlisted account-independent theme and studio preferences.',
  },
  {
    id: 'vehicle-memory-store',
    backend: 'MEMORY',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'vehicle-zustand-store',
    description: 'Zustand vehicle list, telemetry projection and selected context.',
  },
  {
    id: 'notification-memory-store',
    backend: 'MEMORY',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'notification-zustand-store',
    description: 'In-memory notification events and deep-link vehicle context.',
  },
  {
    id: 'realtime-memory-context',
    backend: 'MEMORY',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'realtime-subscription-context',
    description: 'Active realtime subscriptions and account generation context.',
  },
  {
    id: 'fleet-queue-memory-context',
    backend: 'MEMORY',
    scope: 'ACCOUNT',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: false },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'fleet-queue-singleton',
    description: 'Active DomainQueue/SyncOrchestrator account singleton.',
  },
  {
    id: 'command-memory-context',
    backend: 'MEMORY',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'AUTHORITY',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'command-tracker-state',
    description: 'Pending command phase, confirmation and vehicle context.',
  },
  {
    id: 'mavi-memory-context',
    backend: 'MEMORY',
    scope: 'ACCOUNT_VEHICLE',
    sensitivity: 'PRIVATE',
    cleanupPolicies: ['MANAGED_EXTERNALLY', 'PURGE_ON_LOGOUT'],
    namespaceVersion: 1,
    ownerRequirements: { accountId: true, vehicleId: true },
    verifyStrategy: 'CUSTOM',
    customVerifierId: 'mavi-context-future-adapter',
    description: 'Required registry slot; no current persistent mobile Mavi store found.',
  },
];

export function createProductionStorageRegistry(): AccountScopedStorageRegistry {
  const registry = new AccountScopedStorageRegistry();
  for (const descriptor of DESCRIPTORS) {
    registry.registerStorageDescriptor(descriptor);
  }
  registry.freeze();
  return registry;
}

export const PRODUCTION_STORAGE_DESCRIPTOR_COUNT = DESCRIPTORS.length;
